### ISSUE TITLE
[정지현, 이규행 페어]코드리뷰

### ISSUE THREAD

**Issue by 2kyuhang** [Bebeqwer/SpringLV2#1]

**Comment by 2kyuhang** [comment]
사용하지 않는 클래스와 메서드들을 지웠으면 더 깔끔할거 같습니다.
회원가입시 정규식 부분 필요합니다.

**Comment by ironprayer** [comment]
코드가 전체적으로 깔끔하게 작성이 되어있는 것 같습니다. 그리고 Security를 사용해서 Jwt 적용하시는 것도 너무 멋있습니다.

**Comment by ironprayer** [comment]
궁금한 사항들을 올립니다. 답변 주시면 감사하겠습니다.

1. Message 객체에서 Setter를 사용하신 이유가 무엇인가요? 전송해야 하는 데이터의 불변성이 사라지지 않을까요?

2. ResponseEntity에서 따로 Status 코드를 보내는데 Message에도 다시 담아서 보내신 이유가 무엇인가요?

3. DeleteMapping이 Delete에서 ll이라는 변수를 쓰셨던데, 
   의미가 있나요? 어떤 의도의 변수인지 파악하기가 힘든 것 같아요. 적절한 이름으로 변경해보는건 어떠할까요?

4. Service에서 jwtUtil을 가져다 쓰신 이유가 있을까요? filter에서 검증하면서 사용자 정보를 가져오는 방법은 어떠실까요? 

5. DTO 객체의 경우 불변으로 사용해보시는건 어떨까요? 데이터가 중간에 오염이 될 수 있기 때문입니다. 의견을 말씀해주시면 감사하겠습니다.

6. Security부분에서 http add filter부분에 인증,인가 필터가 있던데 흐름상 두 개를 바꿔보는 건 어떠할까요? IOC Container에 빈으로 등록해 문제가 안되지만 문맥상 이야기를 드려봤습니다. 

7. 사용하지 않은 Controller를 남겨두신 이유가 있으실까요? 
   - AuthController

8. System.out.println이 군데군데 보이는데 실제로 필요한 것일까요? 아니면 테스트하면서 남은 걸까요? 주석도 마찬가지입니다. 필요하신 주석들이실까요?

9. Filter가 4개나 존재하는데, jwt 인증, 인가 필터가 추가가 되었다면 AuthFilter는 동작이 겹쳐보입니다. 이렇게 남겨두신 이유가 있으실까요?

**Comment by 2kyuhang** [comment]
사용하지 않는 클래스와 메서드들을 지웠으면 더 좋을듯 합니다.

**Comment by 2kyuhang** [comment]
StatusEnum 로 반환 상태값들을 보내는게 너무 좋을거같습니다.
반대로 사용하지 않는 클래스와 메서드들을 지웠으면 더 좋을듯 합니다.

**Comment by Bebeqwer** [comment]
1.아 참고하겠습니다

2. 이부분은 확인 없이 구글 코드를 가져왔습니다 중복되는 부분인지 여쭤보고 싶습니다
3. 이것도 불찰입니다 그 그냥 가볍게 확인하려고 변수명을 적었다가 나중에 바꾼다는게 깜빡했습니다 
4. 이부분은 추가로 공부해보겠습니다 
5. 불변 개념도 설명해주시면 감사하겠습니다
7 . 강의 내용을 그대로 가져오다보니 필요없는 클래스가 조금 남아있네요 정리하겠습니다
8. 해찬님이 마무리하신부분이라 이부분은 해찬님이 답변해주세용
9 아 남겨둔 이유는 특별히 없습니다 ㅠ 그냥 급하게 과제 마무리한다고 정리를 못했습니다

**Comment by haechanlee96** [comment]
6. 저도 강의 내용을 클론코딩 하다시피 진행한 거라 아직 security 부분을 이해하지 못했습니다.
